#!/usr/bin/env python3
"""
Exemple d'utilisation du système LogementBlockchain
Démontre les fonctionnalités PoW et PoA - Generated By Claude AI
"""

from blockchain import *
from crypto import *
import time


def demo_pow_blockchain():
   """Démonstration avec Proof of Work."""
   print("="*60)
   print("DÉMONSTRATION PROOF OF WORK")
   print("="*60)
   
   # Créer blockchain PoW
   blockchain = LogementBlockchain(difficulty=2, consensus_type='pow')
   print(f"Blockchain PoW créée avec difficulté {blockchain.difficulty}")
   
   # Ajouter des transactions de logement
   transactions = [
      {
         "from": "Alice",
         "to": "Bob",
         "logement_id": "LOG001",
         "action": "transfer_ownership",
         "property_type": "apartment",
         "address": "123 Rue de la Paix, Paris",
         "price": 350000,
         "status": "validated"
      },
      {
         "from": "Bob", 
         "to": "Charlie",
         "logement_id": "LOG002",
         "action": "rental_agreement",
         "property_type": "house",
         "address": "456 Avenue des Champs, Lyon",
         "monthly_rent": 1200,
         "status": "validated"
      },
      {
         "from": "Charlie",
         "to": "David",
         "logement_id": "LOG003",
         "action": "transfer_ownership",
         "property_type": "studio",
         "address": "789 Boulevard Voltaire, Marseille",
         "price": 180000,
         "status": "pending"
      }
   ]
   
   # Ajouter et miner les transactions
   for i, tx in enumerate(transactions):
      print(f"\nAjout transaction {i+1}: {tx['logement_id']}")
      blockchain.add_new_transaction(tx)
      
      print("Mining en cours...")
      start_time = time.time()
      block_index = blockchain.mine()
      mining_time = time.time() - start_time
      
      if block_index:
         print(f"✓ Bloc {block_index} miné en {mining_time:.2f}s")
      else:
         print("✗ Échec du mining")
   
   # Afficher les statistiques
   stats = blockchain.get_chain_stats()
   print(f"\n📊 Statistiques de la blockchain:")
   for key, value in stats.items():
      print(f"  {key}: {value}")
   
   # Afficher les logements validés
   validated = blockchain.get_validated_logements()
   print(f"\n🏠 Logements validés ({len(validated)}):")
   for item in validated:
      tx = item['transaction']
      print(f"  • {tx['logement_id']}: {tx['from']} → {tx['to']} ({tx['action']})")
   
   return blockchain


def demo_poa_blockchain():
   """Démonstration avec Proof of Authority."""
   print("\n" + "="*60)
   print("DÉMONSTRATION PROOF OF AUTHORITY")
   print("="*60)
   
   # Créer blockchain PoA
   blockchain = LogementBlockchain(consensus_type='poa')
   sig_manager = SignatureManager()
   key_manager = KeyManager()
   
   # Générer des clés pour les validateurs
   print("Génération des clés des validateurs...")
   validator1_private, validator1_public, validator1_id = key_manager.generate_key_pair()
   validator2_private, validator2_public, validator2_id = key_manager.generate_key_pair()
   validator3_private, validator3_public, validator3_id = key_manager.generate_key_pair()
   
   # Ajouter les validateurs autorisés
   blockchain.add_validator(validator1_public)
   blockchain.add_validator(validator2_public)
   # validator3 ne sera pas autorisé
   
   print(f"✓ {len(blockchain.get_validators())} validateurs autorisés")
   
   # Transactions immobilières
   transactions = [
      {
         "from": "Notaire_Paris",
         "to": "Client_A",
         "logement_id": "NOTARIAL_001",
         "action": "property_registration",
         "property_type": "villa",
         "address": "12 Rue du Château, Versailles",
         "cadastral_ref": "AB123456",
         "price": 850000,
         "status": "validated"
      },
      {
         "from": "Agency_Lyon", 
         "to": "Client_B",
         "logement_id": "AGENCY_002",
         "action": "rental_contract",
         "property_type": "apartment",
         "address": "34 Place Bellecour, Lyon",
         "monthly_rent": 1800,
         "deposit": 3600,
         "duration_months": 12,
         "status": "validated"
      }
   ]
   
   # Miner avec différents validateurs
   validators = [
      ("Validateur 1", validator1_private, validator1_id),
      ("Validateur 2", validator2_private, validator2_id)
   ]
   
   for i, tx in enumerate(transactions):
      validator_name, validator_key, validator_id = validators[i % len(validators)]
      
      print(f"\nTransaction {i+1}: {tx['logement_id']}")
      blockchain.add_new_transaction(tx)
      
      print(f"Validation par {validator_name}...")
      start_time = time.time()
      block_index = blockchain.mine(private_key_pem=validator_key)
      validation_time = time.time() - start_time
      
      if block_index:
         print(f"✓ Bloc {block_index} validé en {validation_time:.3f}s")
      else:
         print("✗ Échec de la validation")
   
   # Test avec validateur non autorisé
   print(f"\nTest avec validateur non autorisé...")
   blockchain.add_new_transaction({
      "from": "Hacker",
      "to": "Victim", 
      "logement_id": "FRAUD_001",
      "action": "illegal_transfer"
   })
   
   block_index = blockchain.mine(private_key_pem=validator3_private)
   if block_index is None:
      print("✓ Transaction rejetée (validateur non autorisé)")
   else:
      print("✗ ERREUR: Transaction acceptée!")
   
   # Afficher les statistiques
   stats = blockchain.get_chain_stats()
   print(f"\n📊 Statistiques PoA:")
   for key, value in stats.items():
      print(f"  {key}: {value}")
   
   return blockchain


def demo_transaction_queries(blockchain):
   """Démonstration des requêtes sur les transactions."""
   print("\n" + "="*60)
   print("DÉMONSTRATION DES REQUÊTES")
   print("="*60)
   
   # Rechercher par adresse
   print("Transactions impliquant 'Bob':")
   bob_transactions = blockchain.get_transactions_by_address("Bob")
   for item in bob_transactions:
      tx = item['transaction']
      print(f"  • Bloc {item['block_index']}: {tx.get('logement_id', 'N/A')} - {tx.get('action', 'N/A')}")
   
   # Logements validés
   validated = blockchain.get_validated_logements()
   print(f"\nLogements avec statut 'validated' ({len(validated)}):")
   for item in validated:
      tx = item['transaction']
      block_time = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(item['block_timestamp']))
      print(f"  • {tx['logement_id']}: validé le {block_time}")


def demo_chain_persistence():
   """Démonstration de la persistance."""
   print("\n" + "="*60)
   print("DÉMONSTRATION PERSISTANCE")
   print("="*60)
   
   # Créer une blockchain avec des données
   original_blockchain = LogementBlockchain(difficulty=1, consensus_type='pow')
   
   transactions = [
      {"from": "User1", "to": "User2", "logement_id": "SAVE_001", "status": "validated"},
      {"from": "User2", "to": "User3", "logement_id": "SAVE_002", "status": "validated"}
   ]
   
   for tx in transactions:
      original_blockchain.add_new_transaction(tx)
      original_blockchain.mine()
   
   # Exporter
   filename = "blockchain_backup.json"
   original_blockchain.export_chain(filename)
   print(f"✓ Blockchain exportée vers {filename}")
   
   # Importer
   imported_blockchain = LogementBlockchain.import_chain(filename, difficulty=1, consensus_type='pow')
   print(f"✓ Blockchain importée depuis {filename}")
   
   # Vérifier
   original_stats = original_blockchain.get_chain_stats()
   imported_stats = imported_blockchain.get_chain_stats()
   
   print("Comparaison:")
   print(f"  Blocs originaux: {original_stats['total_blocks']}")
   print(f"  Blocs importés: {imported_stats['total_blocks']}")
   print(f"  Transactions originales: {original_stats['total_transactions']}")
   print(f"  Transactions importées: {imported_stats['total_transactions']}")
   
   # Nettoyer
   import os
   if os.path.exists(filename):
      os.remove(filename)
      print(f"✓ Fichier {filename} supprimé")


def main():
   """Fonction principale de démonstration."""
   print("🏠 SYSTÈME BLOCKCHAIN POUR LOGEMENTS")
   print("Démonstration des fonctionnalités PoW et PoA")
   
   # Démonstrations
   pow_blockchain = demo_pow_blockchain()
   poa_blockchain = demo_poa_blockchain()
   
   # Requêtes sur la blockchain PoW
   demo_transaction_queries(pow_blockchain)
   
   # Persistance
   demo_chain_persistence()
   
   print("\n" + "="*60)
   print("DÉMONSTRATION TERMINÉE")
   print("="*60)
   print("✓ Blockchain PoW: Mining basé sur la difficulté")
   print("✓ Blockchain PoA: Validation par autorités certifiées")
   print("✓ Transactions de logement sécurisées")
   print("✓ Requêtes et statistiques")
   print("✓ Import/Export de données")


if __name__ == '__main__':
   main()